backend:
  name: git-gateway
  branch: master

# When using local development proxy
local_backend: true

# Media files will be stored in the repo under public/images
media_folder: "public/images"
# The src attribute for uploaded media will begin with /images
public_folder: "/images"

collections:
  - name: "home"
    label: "Home Page"
    files:
      - file: "src/content/index.md"
        label: "Home Page"
        name: "homePage"
        fields:
          - label: "Hero Section"
            name: "heroSection"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - {
                  label: "Primary Button Text",
                  name: "primaryBtnText",
                  widget: "string",
                }
              - {
                  label: "Secondary Button Text",
                  name: "secondaryBtnText",
                  widget: "string",
                }
          - label: "Highlights Section"
            name: "highlightsSection"
            widget: "object"
            fields:
              - { label: "Section Title", name: "title", widget: "string" }
              - { label: "Section Emoji", name: "emoji", widget: "string" }
              - label: "Highlights"
                name: "highlights"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - {
                      label: "Description",
                      name: "description",
                      widget: "string",
                    }
              - {
                  label: "Highlights Quote",
                  name: "highlightsQuote",
                  widget: "string",
                }
          - label: "Testimonials Section"
            name: "testimonialsSection"
            widget: "object"
            fields:
              - { label: "Section Title", name: "title", widget: "string" }
              - { label: "Section Emoji", name: "emoji", widget: "string" }
              - label: "Testimonials"
                name: "testimonials"
                widget: "list"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Role", name: "role", widget: "string" }
                  - { label: "Content", name: "content", widget: "text" }
                  - { label: "Details", name: "details", widget: "string" }
                  - { label: "Emoji", name: "emoji", widget: "string" }
  - name: "about"
    label: "About Page"
    files:
      - file: "src/content/about.md"
        label: "About Page"
        name: "aboutPage"
        fields:
          - label: "About Section"
            name: "aboutSection"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Emoji", name: "emoji", widget: "string" }
              - { label: "details", name: "details", widget: "string" }
              - { label: "Fun Fact", name: "funFact", widget: "string" }
              - label: "Teaching Journey"
                name: "teachingJourney"
                widget: "list"
                fields:
                  - { label: "Emoji", name: "emoji", widget: "string" }
                  - { label: "Text", name: "text", widget: "string" }
  - name: "videos"
    label: "Videos"
    files:
      - file: "src/content/videos.md"
        label: "Videos"
        name: "videosPage"
        fields:
          - label: "Videos Section"
            name: "videosSection"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Emoji", name: "emoji", widget: "string" }
              - label: "Videos"
                name: "videos"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - {
                      label: "Description",
                      name: "description",
                      widget: "string",
                    }
                  - { label: "Video URL", name: "url", widget: "string" }
                  - { duration: "Duration", name: "duration", widget: "string" }
                  - {
                      thumbnail: "Thumbnail",
                      name: "thumbnail",
                      widget: "image",
                    }
