backend:
  name: git-gateway
  branch: master

# When using local development proxy
local_backend: true

# Media files will be stored in the repo under public/images
media_folder: "public/images"
# The src attribute for uploaded media will begin with /images
public_folder: "/images"

collections:
  - name: "home"
    label: "Home Page"
    files:
      - file: "src/content/index.md"
        label: "Home Page"
        name: "homePage"
        fields:
          - label: "Hero Section"
            name: "heroSection"
            widget: "object"
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the hero section in the landing page. Maximum length: 3 words.",
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "string",
                  hint: "Description of the hero section in the landing page. Maximum length: 22 words.",
                }
              - {
                  label: "Primary Button Text",
                  name: "primaryBtnText",
                  widget: "string",
                  hint: "Text for the primary button in the hero section. Maximum length: 2 words.",
                }
              - {
                  label: "Secondary Button Text",
                  name: "secondaryBtnText",
                  widget: "string",
                  hint: "Text for the secondary button in the hero section. Maximum length: 2 words.",
                }
          - label: "Highlights Section"
            name: "highlightsSection"
            widget: "object"
            fields:
              - {
                  label: "Section Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the highlights section in the landing page. Maximum length: 3 words.",
                }
              - {
                  label: "Section Emoji",
                  name: "emoji",
                  widget: "string",
                  hint: "Emoji for the highlights section. Use https://emojipedia.org/ to search and paste emojis.",
                }
              - label: "Highlights"
                name: "highlights"
                widget: "list"
                fields:
                  - {
                      label: "Title",
                      name: "title",
                      widget: "string",
                      hint: "Title of the highlight. Maximum length: 2 words.",
                    }
                  - {
                      label: "Description",
                      name: "description",
                      widget: "string",
                      hint: "Description of the highlight. Maximum length: 15 words.",
                    }
              - {
                  label: "Highlights Quote",
                  name: "highlightsQuote",
                  widget: "string",
                  hint: "Quote for the highlights section. Maximum length: 35 words.",
                }
          - label: "Testimonials Section"
            name: "testimonialsSection"
            widget: "object"
            fields:
              - {
                  label: "Section Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the testimonials section in the landing page. Maximum length: 2 words.",
                }
              - {
                  label: "Section Emoji",
                  name: "emoji",
                  widget: "string",
                  hint: "Emoji for the highlights section. Use https://emojipedia.org/ to search and paste emojis.",
                }
              - label: "Testimonials"
                name: "testimonials"
                widget: "list"
                fields:
                  - {
                      label: "Name",
                      name: "name",
                      widget: "string",
                      hint: "Name of the person writing the testimonial. Example: Dr. Sarah Chen.",
                    }
                  - {
                      label: "Role",
                      name: "role",
                      widget: "string",
                      hint: "Role of the person writing the testimonial. Allowed values: Education Professional / Student / Parent.",
                    }
                  - {
                      label: "Content",
                      name: "content",
                      widget: "text",
                      hint: "The actual testimonial content. Maximum length: 40 words.",
                    }
                  - {
                      label: "Details",
                      name: "details",
                      widget: "string",
                      hint: "Details of the person writing the testimonial. Example: Department Head, Science / Class of 2023 / Parent of AP Chemistry student. Maximum length: 5 words.",
                    }
                  - { label: "Emoji", name: "emoji", widget: "string" }
  - name: "about"
    label: "About Page"
    files:
      - file: "src/content/about.md"
        label: "About Page"
        name: "aboutPage"
        fields:
          - label: "About Section"
            name: "aboutSection"
            widget: "object"
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the about me section. Maximum length: 2 words.",
                }
              - {
                  label: "Emoji",
                  name: "emoji",
                  widget: "string",
                  hint: "Emoji used for the about me section. Use https://emojipedia.org/ to search and paste emojis.",
                }
              - {
                  label: "details",
                  name: "details",
                  widget: "markdown",
                  hint: "Main content for about me section. Use 2-3 paragraphs. Maximum length: 160 words.",
                }
              - {
                  label: "Fun Fact",
                  name: "funFact",
                  widget: "string",
                  hint: "Fun fact about you. Maximum length: 20 words.",
                }
              - {
                  label: "Image",
                  name: "image",
                  widget: "image",
                  hint: "Your image to be used in the about me page. Pick a good one :).",
                }
              - label: "Teaching Journey"
                name: "teachingJourney"
                widget: "list"
                fields:
                  - {
                      label: "Emoji",
                      name: "emoji",
                      widget: "string",
                      hint: "Emoji used for teaching journey point. Use https://emojipedia.org/ to search and paste emojis.",
                    }
                  - {
                      label: "Text",
                      name: "text",
                      widget: "string",
                      hint: "Point to be shown in the teaching journey card. The foramt should be like this - [area]: [description about area]. Use quantifiable points wherever possible. For example:\nTeaching Experience: 20+ years across USA and India. Maximum length: 12 words.",
                    }
  - name: "videos"
    label: "Videos Page"
    files:
      - file: "src/content/videos.md"
        label: "Videos"
        name: "videosPage"
        fields:
          - label: "Videos Section"
            name: "videosSection"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Emoji", name: "emoji", widget: "string" }
              - label: "Videos"
                name: "videos"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - {
                      label: "Description",
                      name: "description",
                      widget: "string",
                    }
                  - { label: "Video URL", name: "url", widget: "string" }
                  - {
                      thumbnail: "Thumbnail",
                      name: "thumbnail",
                      widget: "image",
                    }
