backend:
  name: git-gateway
  branch: master

local_backend: true

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "home"
    label: "Home Page"
    files:
      - file: "src/content/index.md"
        label: "Home Page"
        name: "homePage"
        fields:
          - label: "Hero Section"
            name: "heroSection"
            widget: "object"
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the hero section in the landing page. Maximum length: 3 words.",
                  pattern:
                    [
                      '^(?:\s*\S+(?:\s+\S+){0,2}\s*)$',
                      "Must be 3 words or less",
                    ],
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "string",
                  hint: "Description of the hero section in the landing page. Maximum length: 22 words.",
                  pattern:
                    [
                      '^(?:\s*\S+(?:\s+\S+){0,21}\s*)$',
                      "Must be 22 words or less",
                    ],
                }
              - {
                  label: "Primary Button Text",
                  name: "primaryBtnText",
                  widget: "string",
                  hint: "Text for the primary button in the hero section. Maximum length: 2 words.",
                  pattern:
                    [
                      '^(?:\s*\S+(?:\s+\S+){0,1}\s*)$',
                      "Must be 2 words or less",
                    ],
                }
              - {
                  label: "Secondary Button Text",
                  name: "secondaryBtnText",
                  widget: "string",
                  hint: "Text for the secondary button in the hero section. Maximum length: 2 words.",
                  pattern:
                    [
                      '^(?:\s*\S+(?:\s+\S+){0,1}\s*)$',
                      "Must be 2 words or less",
                    ],
                }
          - label: "Highlights Section"
            name: "highlightsSection"
            widget: "object"
            fields:
              - {
                  label: "Section Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the highlights section in the landing page. Maximum length: 3 words.",
                  pattern:
                    [
                      '^(?:\s*\S+(?:\s+\S+){0,2}\s*)$',
                      "Must be 3 words or less",
                    ],
                }
              - {
                  label: "Section Emoji",
                  name: "emoji",
                  widget: "string",
                  hint: "Emoji for the highlights section. Use https://emojipedia.org/ to search and paste emojis.",
                }
              - label: "Highlights"
                name: "highlights"
                widget: "list"
                fields:
                  - {
                      label: "Title",
                      name: "title",
                      widget: "string",
                      hint: "Title of the highlight. Maximum length: 2 words.",
                      pattern:
                        [
                          '^(?:\s*\S+(?:\s+\S+){0,1}\s*)$',
                          "Must be 2 words or less",
                        ],
                    }
                  - {
                      label: "Description",
                      name: "description",
                      widget: "string",
                      hint: "Description of the highlight. Maximum length: 15 words.",
                      pattern:
                        [
                          '^(?:\s*\S+(?:\s+\S+){0,14}\s*)$',
                          "Must be 15 words or less",
                        ],
                    }
              - {
                  label: "Highlights Quote",
                  name: "highlightsQuote",
                  widget: "string",
                  hint: "Quote for the highlights section. Maximum length: 35 words.",
                  pattern:
                    [
                      '^(?:\s*\S+(?:\s+\S+){0,34}\s*)$',
                      "Must be 35 words or less",
                    ],
                }
          - label: "Testimonials Section"
            name: "testimonialsSection"
            widget: "object"
            fields:
              - {
                  label: "Section Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the testimonials section in the landing page. Maximum length: 2 words.",
                  pattern:
                    [
                      '^(?:\s*\S+(?:\s+\S+){0,1}\s*)$',
                      "Must be 2 words or less",
                    ],
                }
              - {
                  label: "Section Emoji",
                  name: "emoji",
                  widget: "string",
                  hint: "Emoji for the highlights section. Use https://emojipedia.org/ to search and paste emojis.",
                }
              - label: "Testimonials"
                name: "testimonials"
                widget: "list"
                fields:
                  - {
                      label: "Name",
                      name: "name",
                      widget: "string",
                      hint: "Name of the person writing the testimonial. Example: Dr. Sarah Chen.",
                    }
                  - {
                      label: "Role",
                      name: "role",
                      widget: "string",
                      hint: "Role of the person writing the testimonial. Allowed values: Education Professional / Student / Parent.",
                      pattern:
                        [
                          "^(Education Professional|Student|Parent)$",
                          "Must be one of: Education Professional, Student, or Parent",
                        ],
                    }
                  - {
                      label: "Content",
                      name: "content",
                      widget: "text",
                      hint: "The actual testimonial content. Maximum length: 60 words.",
                      pattern:
                        [
                          '^(?:\s*\S+(?:\s+\S+){0,59}\s*)$',
                          "Must be 60 words or less",
                        ],
                    }
                  - {
                      label: "Details",
                      name: "details",
                      widget: "string",
                      hint: "Details of the person writing the testimonial. Example: Department Head, Science / Class of 2023 / Parent of AP Chemistry student. Maximum length: 5 words.",
                      pattern:
                        [
                          '^(?:\s*\S+(?:\s+\S+){0,4}\s*)$',
                          "Must be 5 words or less",
                        ],
                    }
                  - { label: "Emoji", name: "emoji", widget: "string" }
  - name: "about"
    label: "About Page"
    files:
      - file: "src/content/about.md"
        label: "About Page"
        name: "aboutPage"
        fields:
          - label: "About Section"
            name: "aboutSection"
            widget: "object"
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the about me section. Maximum length: 2 words.",
                  pattern:
                    [
                      '^(?:\s*\S+(?:\s+\S+){0,1}\s*)$',
                      "Must be 2 words or less",
                    ],
                }
              - {
                  label: "Emoji",
                  name: "emoji",
                  widget: "string",
                  hint: "Emoji used for the about me section. Use https://emojipedia.org/ to search and paste emojis.",
                }
              - {
                  label: "details",
                  name: "details",
                  widget: "markdown",
                  hint: "Main content for about me section. Use 2-3 paragraphs. Maximum length: 200 words.",
                  pattern:
                    [
                      '^(?:\s*\S+(?:\s+\S+){0,199}\s*)$',
                      "Must be 200 words or less",
                    ],
                }
              - {
                  label: "Fun Fact",
                  name: "funFact",
                  widget: "string",
                  hint: "Fun fact about you. Maximum length: 20 words.",
                  pattern:
                    [
                      '^(?:\s*\S+(?:\s+\S+){0,19}\s*)$',
                      "Must be 20 words or less",
                    ],
                }
              - {
                  label: "Image",
                  name: "image",
                  widget: "image",
                  hint: "Your image to be used in the about me page. Pick a good one :).",
                }
              - label: "Teaching Journey"
                name: "teachingJourney"
                widget: "list"
                fields:
                  - {
                      label: "Emoji",
                      name: "emoji",
                      widget: "string",
                      hint: "Emoji used for teaching journey point. Use https://emojipedia.org/ to search and paste emojis.",
                    }
                  - {
                      label: "Text",
                      name: "text",
                      widget: "string",
                      hint: "Point to be shown in the teaching journey card. The format should be like this - [area]: [description about area]. Use quantifiable points wherever possible. For example:\nTeaching Experience: 20+ years across USA and India. Maximum length: 12 words.",
                      pattern:
                        [
                          '^(?:\s*\S+(?:\s+\S+){0,11}\s*)$',
                          "Must be 12 words or less",
                        ],
                    }
  - name: "videos"
    label: "Videos Page"
    files:
      - file: "src/content/videos.md"
        label: "Videos"
        name: "videosPage"
        fields:
          - label: "Videos Section"
            name: "videosSection"
            widget: "object"
            fields:
              - {
                  label: "Title",
                  name: "title",
                  widget: "string",
                  hint: "Title of the videos section. Maximum length: 2 words.",
                  pattern:
                    [
                      '^(?:\s*\S+(?:\s+\S+){0,1}\s*)$',
                      "Must be 2 words or less",
                    ],
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "string",
                  hint: "Description of the videos section. Maximum length: 15 words.",
                  pattern:
                    [
                      '^(?:\s*\S+(?:\s+\S+){0,14}\s*)$',
                      "Must be 15 words or less",
                    ],
                }
              - {
                  label: "Emoji",
                  name: "emoji",
                  widget: "string",
                  hint: "Emoji for the videos section. Use https://emojipedia.org/ to search and paste emojis.",
                }
              - label: "Videos"
                name: "videos"
                widget: "list"
                fields:
                  - {
                      label: "Title",
                      name: "title",
                      widget: "string",
                      hint: "Title of the YouTube video. Maximum length: 7 words.",
                      pattern:
                        [
                          '^(?:\s*\S+(?:\s+\S+){0,6}\s*)$',
                          "Must be 7 words or less",
                        ],
                    }
                  - {
                      label: "Description",
                      name: "description",
                      widget: "string",
                      hint: "Description of the YouTube video. Maximum length: 20 words.",
                      pattern:
                        [
                          '^(?:\s*\S+(?:\s+\S+){0,19}\s*)$',
                          "Must be 20 words or less",
                        ],
                    }
                  - {
                      label: "Video URL",
                      name: "url",
                      widget: "string",
                      hint: "URL of the youtube video. Example: https://www.youtube.com/watch?v=HRiRtzyl0N0",
                      pattern:
                        [
                          'https:\/\/www\.youtube\.com\/watch\?v=[\w-]+',
                          "Must be a valid YouTube video URL",
                        ],
                    }
                  - {
                      label: "Thumbnail",
                      name: "thumbnail",
                      widget: "image",
                      hint: "Thumbnail to be used for the youtube video card. Pick a good one :).",
                    }
